### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by tyoshino** [w3c/webappsec-credential-management#10]
Maybe it's a typo

https://w3c.github.io/webappsec-credential-management/#monkey-patching-fetch-3

```
If r’s url is not the same as r’s client’s origin, ...
```

this should be

```
If r’s url's origin is not the same as r’s client’s origin, 
```

**Comment by AxelNennker** [comment]
This fixed, right? The text now talks about "host" and "scheme"

**Comment by tyoshino** [comment]
Oh, right. So, yes, this issue is now obsolete. Thanks
