### ISSUE TITLE
[[Store]] implementations should be able to fail.

### ISSUE THREAD

**Issue by jyasskin** [w3c/webappsec-credential-management#107]
https://w3c.github.io/webappsec-credential-management/#dom-credential-store-slot doesn't say that [[Store]] returns anything, but the call to it in https://w3c.github.io/webappsec-credential-management/#algorithm-store uses the return value to resolve a promise. WebAuthn wants to reject that promise, and other storage algorithms should probably be able to report failure too.

Because [[Store]] runs in parallel, it looks not-ok to call https://www.w3.org/2001/tag/doc/promises-guide#a-new-promise (right @domenic?), so the Credential Management call to [[Store]] should probably accept both success and failure results instead of expecting [[Store]] to return a Promise.

**Comment by domenic** [comment]
Right, no new promises can be created in parallel without queuing a task.
