### ISSUE TITLE
`SiteBoundCredential::name` should be `DOMString`.

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec-credential-management#14]
Not `USVString`.

**Comment by annevk** [comment]
Does it not go over the network?

**Comment by mikewest** [comment]
It does. Does that mean it has to be `USVString`? I thought `USVString` was basically just for URLs...

**Comment by annevk** [comment]
USVString is for things that get utf-8 encoded at some point.

**Comment by mikewest** [comment]
For clarity, it goes over the network, but after being either encoded via URLSearchParams or FormData's encoding algorithms.

**Comment by mikewest** [comment]
Ok, so even post bodies need to be populated from USVStrings. I can do that. ;)
