### ISSUE TITLE
Some example code don't work

### ISSUE THREAD

**Issue by agektmr** [w3c/webappsec-credential-management#15]
Sample code in [Post-sign-in Confirmation](https://w3c.github.io/webappsec-credential-management/#examples-post-signin) and [Change Password](https://w3c.github.io/webappsec-credential-management/#examples-change-password) doesn't work. It returns `Uncaught TypeError: Failed to construct 'PasswordCredential': 'id' must not be empty.` error.  
This is caused by `input` elements missing `name` attribute.

**Comment by vabr-g** [comment]
I filed https://github.com/w3c/webappsec-credential-management/issues/35 for the question whether the spec should allow construction from `id` attribute after all.
