### ISSUE TITLE
Examples in the wild

### ISSUE THREAD

**Issue by SilentImp** [w3c/webappsec-credential-management#164]
Hi,
maybe you could provide me with some example in the wild?
I find this API great and trying to implement it on the project I am currently working on (werkspot.nl) as a progressive enhancement to the current flow.
The problem I face: it doesn't have enough trust, because I am not able to give usage examples of GMAIL or Facebook level =__='.
So I would be very grateful for any good usage examples in the wild.
Regards. Anton.

**Comment by SilentImp** [comment]
With the help of kind Mr Eiji Kitamura, I was able to figure out that this API is being applied on Twitter and Instagram.
This rise question: maybe it's would be a good idea aside from "caniuse" blocks with browser support in the spec add some kind of "whereitused" ones? Because I believe that it's really useful where you have an intent to implement something like this in the project you are working on.

**Comment by equalsJeffH** [comment]
> With the help of kind Mr Eiji Kitamura, I figured out that this API is used on Twitter and Instagram.

We're glad Eiji was able to help you.  (thx @agektmr!)

> question: maybe it would be a good idea, aside from "caniuse" blocks with browser support in the specification, to add "whereitused" ones? Because I believe that it's beneficial when you intend to implement something like this in a real-life project.

It seems you are essentially requesting a "how to use the credential management (CredMan) API" document that uses examples from the wild. The closest I'm aware of is the [How to FIDO](https://github.com/fido-alliance/how-to-fido/blob/master/HowToFIDO.md) doc (though it presently focuses on using WebAuthn/FIDO (aka Public Key credentials)). Eventually, if there were appropriate editorial resources applied, the latter document could perhaps illustrate how to use the CredMan API to weave together use of password, federated, and public key (webauthn/fido) creds, and facilitating migration to public key creds.

> add "whereitused" ones

AFAIK such things do not at this time exist and creating them would be an entirely separate project (and I'm unsure whether it's practical). FYI, I suspect what you are calling the "caniuse" blocks are, for example, the "MDN" blocks in the webauthn spec (e.g., [here](https://www.w3.org/TR/webauthn-2/#iface-pkcredential) on the right edge), which leverage back-end data managed by the Mozilla Developer Network (MDN).
