### ISSUE TITLE
Fix build

### ISSUE THREAD

**Issue by nsatragno** [w3c/webappsec-credential-management#213]
Fix the build. It is failing with "No 'dfn' refs found for 'parent browsing context'."

**Comment by lukewarlow** [comment]
Does this need a new reference or to just change it to not be a reference for now?

**Comment by sideshowbarker** [comment]
I can help with this if needed

**Comment by nsatragno** [comment]
Yeah I'd appreciate it. I can't easily find when the definition went away, and what the new equivalent is. Cheers!
