### ISSUE TITLE
Please PLEASE please auto-publish this spec

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webappsec-credential-management#226]
Can we please put this spec on auto-publish. We just wasted a bunch of time looking at the outdated stuff on /TR/ only to find differences in the Editor's draft 😭 

The spec on TR is like 4 years out of date. That's not great and really unnecessary. It takes like 5 minutes to set up auto-publish to TR.

**Comment by nsatragno** [comment]
Sorry you went through that, I agree we should do this. I'll get to it, I need to fix my account's permissions on this repo first.

**Comment by nsatragno** [comment]
I managed to get the action to push it to echidna, but then it fails with a bunch of errors:

https://lists.w3.org/Archives/Public/public-tr-notifications/2024Feb/0274.html

I'll see if I can figure these out tomorrow

**Comment by nsatragno** [comment]
Done!

**Comment by marcoscaceres** [comment]
You are the best, @nsatragno! Thank you so much!
