### ISSUE TITLE
User activation 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webappsec-credential-management#241]
See https://github.com/WICG/digital-credentials/issues/91 ... the question is, should Cred Man deal with user activation requirements? 

And if so, should we enforce "[fully active descendant of a top-level traversable with user attention](https://html.spec.whatwg.org/multipage/interaction.html#fully-active-descendant-of-a-top-level-traversable-with-user-attention)"

@nsatragno, on the Chromium side - with Password and Federated credentials - do you consume the user activation? Also, clearly I think the document should have system focus.

**Comment by nsatragno** [comment]
There's no user activation requirement for password, federated, fedcm, or (normally) webauthn credentials on Chromium. Safari has some special sauce for webauthn where you get a "free" activation when the page is first loaded and need a user gesture to trigger subsequent requests.

The only case I can think of a credman credential consuming a user activation in a standardized way is [webauthn in a cross-origin make credential request](https://w3c.github.io/webauthn/#:~:text=If%20sameOriginWithAncestors%20is,relevant%20global%20object.). I would be inclined to have the digital identity credentials spec handle it itself considering this.

**Comment by marcoscaceres** [comment]
Ok, cool. Will handle it there and go see about the magic sauce. Maybe we can upstream that to HTML.
