### ISSUE TITLE
PasswordCredential(HTMLFormElement form) Constructor typo?

### ISSUE THREAD

**Issue by jonathanKingston** [w3c/webappsec-credential-management#26]
PasswordCredential(HTMLFormElement form) Constructor 3.1.3.1: under the Otherwise step: **9.3** mentions:
`Set c’s additionalData attribute to formData.`

Should this be: `Set c’s additionalData attribute to params.`

**Comment by vabr-g** [comment]
Indeed!

**Comment by vabr-g** [comment]
Thanks again for the report. The above merge should have fixed it.
