### ISSUE TITLE
PasswordCredential(HTMLFormElement form) may fail in valid password change form cases

### ISSUE THREAD

**Issue by battre** [w3c/webappsec-credential-management#34]
The following form is a valid change password form that fails to be parsed by the PasswordCredential(HTMLFormElement form) constructor
```
<form action="https://example.com/login" method="POST" id="theForm">
  <label for="username">Username</label>
  <input type="text" id="username" name="username" autocomplete="username">
  <label for="new-password">New Password</label>
  <input type="text" id="new-password" name="new-password" autocomplete="new-password">
  <label for="old-password">Old Password</label>
  <input type="text" id="old-password" name="old-password" autocomplete="current-password">
  <input type="submit">
</form>
```

The PasswordCredential(HTMLFormElement form) constructor is sensitive to the order of "current-password" and "new-password" fields. It takes the last one and stores it in the credential. In the example above, the old password gets saved, not the new one.

**Comment by vabr-g** [comment]
I guess that type="text" for password fields also does not help (see https://github.com/w3c/webappsec-credential-management/issues/36).
