### ISSUE TITLE
should incumbent settings object be relevant settings object?

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webappsec-credential-management#53]
`incumbent settings object` is utilized in several places in the spec, although there's this warning [in the HTML spec here](https://html.spec.whatwg.org/#concept-incumbent-everything) (scroll down below the example):
> Warning: The incumbent and entry concepts should not be used by new specifications, as they are excessively complicated and unintuitive to work with\. We are working to remove almost all existing uses from the platform:​ see issue \#1430 for incumbent, and issue \#1431 for entry\.

Should this spec be using the [`relevant settings object`](https://html.spec.whatwg.org/#relevant-settings-object) instead?

**Comment by domenic** [comment]
Thanks for filing! This is very important to fix. I've added it to our master list at https://github.com/whatwg/html/issues/1430.

**Comment by battre** [comment]
Talked to Mike, this should be current settings object.

**Comment by equalsJeffH** [comment]
in examining index.src.html in the master branch (at commit 1c700aa), it seems to me this issue has been fixed. yes?
