### ISSUE TITLE
origin concept and algorithms

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webappsec-credential-management#64]
the cred mgmt spec presently cites RFC6454 for origin stuff -- it perhaps ought to use:

https://html.spec.whatwg.org/#concept-origin
https://html.spec.whatwg.org/#concept-origin-effective-domain
https://html.spec.whatwg.org/#ascii-serialisation-of-an-origin
etc...

**Comment by mikewest** [comment]
I agree! Thanks for flagging this.

**Comment by vabr-g** [comment]
The above merged commit and https://github.com/w3c/webappsec-credential-management/commit/3944f7e85d29ba0b3b0f583789a1ae2de7740071 should have fixed this.

**Comment by equalsJeffH** [comment]
[wow, didn't realize u folks would jump on this so quickly]  just to note: unfortunately, html.spec's origin stuff does not present the background/context/motivation material that's in RFC6454 -- so I'd be inclined to informatively reference the latter.
