### ISSUE TITLE
Feature request: Add API for android finger print reader

### ISSUE THREAD

**Issue by BorntraegerMarc** [w3c/webappsec-credential-management#71]
Steps to reproduce the problem:
So, I wanted to develop a progressive web app where the user can log in with his finger print. But unfortunately there is no API on how to check the users finger is valid.

----- DISCLAIMER -----
I know that this is the wrong place to post a feature request. But I didn't find the right place. So if you could point me in the right direction, that would be awesome :)

What is the expected behavior?
So I see different very helpful use cases for this API:
- Provide strong authentication with two factor authentication for an web app
- Simple sign on process for web app

The registration process probably would look similar to the subscription process for web push notifications.

**Comment by battre** [comment]
https://www.w3.org/TR/webauthn/ will provide the foundations for what you want to build.

**Comment by BorntraegerMarc** [comment]
This is awesome @battre thanks! Do you have any idea when it will be released?

**Comment by battre** [comment]
There are some discussions about merging the API with the credential management api and then creating an implementer's draft. I don't have any concrete timelines but everybody is eager to start implementing WebAuthN.
