### ISSUE TITLE
Expose passwords to JavaScript

### ISSUE THREAD

**Issue by battre** [w3c/webappsec-credential-management#75]
The Credential Manager API put a lot of effort into concealing passwords from the JavaScript of the web page by monkey patching Fetch. This was justified with preventing XSS attacks, but we learned that those attacks are still possible unless the site owner does [more work](https://www.w3.org/TR/credential-management/#security-same-origin-leakage). For example, the credentials could be posted to an endpoint that reflects the content back (e.g. by posting to a forum that displays the content, i.e. the credentials, as a user contribution, or by posting to the login-system after swapping the form names of username and password, so that the login-system would complain "no user 123456 exists", see [Issue 58](https://github.com/w3c/webappsec-credential-management/issues/58)).

Besides that, we received feedback that the API was hard to use:
* Some site struggled with the fact that credentials would be received as HTTP form posts but wanted JSON objects.
* Another site preferred to hash the password before sending it over the wire.

Given that the protection was not as effective as desired and that the concealing of passwords has usability problems, we suggest to share the password with JavaScript directly and deprecate the current limitation in the Chrome implementation gracefully while reaching out to current users of the API.

**Comment by battre** [comment]
Here is the corresponding pull request: https://github.com/w3c/webappsec-credential-management/pull/76

**Comment by AngeloKai** [comment]
Does this mean the related PR on the Fetch spec that MikeW filed a while ago will not be needed? I saw that PR a while back but haven't been able to find it.

**Comment by battre** [comment]
That is correct, we would not need the PR on the Fetch spec.

**Comment by battre** [comment]
Fixed with https://github.com/w3c/webappsec-credential-management/pull/76
