### ISSUE TITLE
Spec is unclear on what the promise returned by store() is resolved with (Credential/undefined)

### ISSUE THREAD

**Issue by ghost** [w3c/webappsec-credential-management#98]
> [Exposed=Window, SecureContext]
> interface CredentialsContainer {
>   Promise<Credential?> get(optional CredentialRequestOptions options);
>   Promise<Credential> store(Credential credential);
>   Promise<Credential?> create(optional CredentialCreationOptions options);
>   Promise<void> preventSilentAccess();
> };

The method signature says that the promise returned by store(credential) should be resolved with a Credential object. However, step 5 in [Store a Credential](https://w3c.github.io/webappsec-credential-management/#abstract-opdef-store-a-credential) says:
> Run the following steps in parallel:
> 1. Let r be the result of executing credential’s interface object's \[\[Store\]\](credential) internal method on credential.
> 2. Resolve p with r.

And \[\[Store\]\](credential) internal method as described in section [Credential Internal Methods](https://w3c.github.io/webappsec-credential-management/#dom-credential-store-slot) doesn't have any return value. So there is no information what is the returned Credential object.

**Comment by wmhilton** [comment]
This is a source of confusion for developers (or at least for me!). Source: https://twitter.com/agektmr/status/929526859817148416

**Comment by battre** [comment]
+ @mikewest 

WebAuthN returns a `DOMException` for `[[Store]](credential)`. Should we return some kind of void-ness?

**Comment by mikewest** [comment]
Chrome's current implementation resolves with `undefined`. It's not clear why we'd want to reject with a `DOMException` instead. Changing step 5.2 of [store a credential](https://w3c.github.io/webappsec-credential-management/#abstract-opdef-store-a-credential) to "Resolve |p| with `undefined`." seems like the right thing to do here, consistent with the suggestions in https://www.w3.org/2001/tag/doc/promises-guide/#one-and-done.

**Comment by battre** [comment]
I am saying that WebAuhN rejects: https://w3c.github.io/webauthn/#storeCredential
For passwords / federated credentials, `undefined` SGTM.

I was wondering whether [PasswordCredential's [Store](https://w3c.github.io/webappsec-credential-management/#store-passwordcredential) should say "... and returns `undefined` once ..." to be more explicit so that "Let r be the result of executing credential’s interface object's [[Store]](credential) internal method on credential." (see above) makes more sense.

**Comment by mikewest** [comment]
> I am saying that WebAuhN rejects: https://w3c.github.io/webauthn/#storeCredential

I'd suggest not doing that.

> For passwords / federated credentials, undefined SGTM.

Addressed as part of the PR for https://github.com/w3c/webappsec-credential-management/pull/114.
